[package]
name = "my-database"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1"
tokio = { version = "1", features = ["full"] }
futures = "0.3"
toml = "0.8.20"
serde = { version = "1.0.219", features = ["derive"] }
log = "0.4.27"
env_logger = "0.11.8"
